plugin: improve the unwrap by using expect
caused by the following crash

2023-12-29T21:29:41.278Z UNUSUAL hsmd: HSM: created new hsm_secret file
thread 'main' panicked at /home/vincent/.cargo/git/checkouts/cln4rust-0de0305144cd79e4/020cc5f/plugin/src/types.rs:28:69:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-12-29T21:29:41.458Z INFO    plugin-folgore_plugin: Killing plugin: exited before we sent init
The Bitcoin backend died.

Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>